version: '3.7'
services:
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongo_storage:/data/db

  server:
    image: server:latest
    build: ./server
    ports: 
      - 8080:8080   

volumes:
  mongo_storage: