version: '3.7'
services:
  
  brogrammers-db:
    image: lings24/brogrammers-db:1.0
    ports:
      - 27017:27017
    volumes:
      - mongo_storage:/data/db
    networks:
      - brogrammers-network
    environment:
      - MONGO_INITDB_DATABASE=toDoList

  brogrammers-ui:
    image: lings24/brogrammers-ui:1.0
    ports:
      - 80:3000
    networks:
      - brogrammers-network

  brogrammers-server:
    image: lings24/brogrammers-server:1.0
    ports: 
      - 8080:8080
    networks:
      - brogrammers-network

networks:
  brogrammers-network:

volumes:
  mongo_storage: